### PR TITLE
beginning overhaul of random processes

### PR DESCRIPTION
**Pull request by dlsun**
Overhauling random processes.

All random processes (Markov chains, Poisson processes, Gaussian processes) have a corresponding:
- result object that stores one realization
- `ProbabilitySpace`
- `RandomProcess`

Arrival times, interarrival times, and states are now functions defined on the probability space.

### CODE REVIEW

**Comment by kevindavisross** [comment]
I've played around with some of the new random process features, but I haven't really looked at most of the code.  I really like the separate ProbabilitySpace and RandomProcess definitions.  And lots of the features seem to be working properly, e.g. returning the correct distributions.  Here are some initial thoughts.

**Suggested Fixes**
- Need to be able to plot sample paths of discrete time MC (I think you said you were working on this)
- For Brownian motion, `Var(X[t]) = scale * t`, but I think it is more standard to define `scale` so that `Var(X[t]) = scale**2 * t`
- Can we start the arrival time sequence at 0?  I think it's standard to define the 0th `arrival_time` as 0, so that `W[1]` is the time of the actual first arrival.  
- Likewise, if we want the time of the first arrival to be equal to the first interarrival time, `W[1] = T[1]`, then we need the `interarrival_time` sequence to start with 0 also.
- 
```
P = MarkovChainProbabilitySpace(...)
X = RandomProcess(P)
X.draw()
```
returns `ContinuousTimeFunction` rather than a state sequence (and `X.sim(1)` returns blank Result).
- You had one example that was `X = RandomProcess(GaussianProcess)` which didn't always work (e.g. `(X[1] & X[2]).sim(100)` returned an error).  We should maybe include warning messages that it's either `X = RandomProcess(GaussianProcessProbabilitySpace)` or `X=GaussianProcess` but not a mix of the two.


**Comments/questions**
- We can call RV like a function to find its value for a particular probability space outcome.  Can we do something similar for random process objects?  For example, save one draw from a `PoissonProcessProbabilitySpace` as `omega` and then access the sample path, arrival times, and interarrival times for this particular outcome.
- When defining a `RandomProcess` on a probability space, should there be available an explicit "identity" function, maybe `sample_path`, so that `X = RandomProcess(P)` is equivalent to `X = RandomProcess(P, sample_path)`?  
- Is it possible to define independent *probability spaces* for any of the new objects?  For example, I can add independent Poisson Processes by defining two independent `PoissonProcess`es and using `AssumeIndependent`.  But would it be possible to define a probability space supporting two independent Poisson processes, `P = PoissonProcessProbabilitySpace(...)*PoissonProcessProbabilitySpace(...)`, with a result object equal to a product of two result objects, and then define processes on this space like `N = RandomProcess(P[0])`?  I assume `AssumeIndependent` is doing something like this under the hood, but when I try to define independent PPPS's directly I get an error.  
- `arrival_times` works nicely when first defining a probability space.  But how to get arrival times for a general discrete state continuous time random process?  Is something like the following possible?

```
N = PoissonProcess(...)
W = N.apply(arrival_times) # or W = arrival_times(N)
```
For example, if I add two independent Poisson processes using `AssumeIndependent` as mentioned above I might want to find the arrival times of the resulting process.
- In general, how do we apply functionals to a random process?  Like defining stopping times.  I think I need to understand better what the various results objects are and what they can do.
- It would be helpful to define a degenerate `RandomProcess` $X(t) = t$, called `Time`?, which can be used with any probability space.  For example, `X = N - Time`.  (I think you did something similar for constants as `RV`.)
- Is there a `states` function for general continuous time discrete state processes, to return the sequence of states, `S = RV(P, states)`.


I'll continue reviewing and post some notebooks later.  Thanks!

**Comment by dlsun** [comment]
@kevindavisross 

I haven't had a chance to address the RandomProcess issues you raised above, but that's next on my list.

What I've done is overhaul the underlying data structures for vectors, infinite vectors, discrete-time functions, etc. I think we should be back to the old functionality based on my tests, but I'm sure I missed a few things. Could you run through your notebooks and tutorial and let me know if there are any bugs I should fix?

**Comment by dlsun** [comment]
Fixed all of the bugs that you reported, except for the one about "Simulating paths of a process along with things like arrival times" (this is on my TODO list).

**Comment by dlsun** [comment]
The last few commits essentially remove `RandomProcess`, as we discussed offline. `RandomProcess` still exists in barebones form, mostly for defining processes like random walks and AR processes. For this use case, it is more common to specify the probability space and the index set, but not the function. So I changed the API back to `RandomProcess(probSpace, index_set, function)`.

Right now, random walks and AR processes are very slow. It takes a long time to evaluate X[n] for n > 20. This is a known issue, and I'm working on fixing this. Let me know if you spot any other bugs.

**Comment by kevindavisross** [comment]
I'll email you some notebooks with examples.  I ran some of the tests of binary operations you suggested.  Most seem to work the way they should.  A few questions

- How do we want Vector (or InfiniteVector) + ContinuousTimeFunction to behave (both for RV and result)?  At first I thought this wouldn't make sense.  But do we want (2, 3) + X(t) to return (2 + X(t), 3 + X(t))?  Same for DiscreteTimeFunction.
- What kind of Python object is a Symbulate result vector?  Vector + [blank] works when Vector is a result vector, e.g. `x + RV(Normal(0, 1))` returns RV-Vector for `x = Poisson(2)**2.draw()`.  But how to replace x with constants, e.g. (2, 3) + RV(Normal(0, 1))?  I tried numpy array but that's not it.
- I'm assuming we only want to allow operations on Vectors with same length, so Vector + Infinite-Vector should not work, and it does not (i.e. no recycling).

Other comments/questions
- Can you give me a few examples of `DiscreteTimeFunction`?  I'm not sure how this is intended to work.
- We now have ContinuousTimeFunction result.  Are GaussianProcessResult and PoissonProcessResult special cases of CTF result?  Will each special process have its own result type, or should there just be general CTF result?
- What are the intended "rules" for unpacking?  Generally, `X = RV(P * Q)` gets unpacked like `X[0] = RV(P), X[1] = RV(Q)`.  But not if `P` and `Q` represent Scalar and Vector, in which case it gets unpacked like one big vector.  For example,
```
X = RV(Poisson(1) * (Normal(0, 1) ** 2))
X[1]  # is RV(Normal(0, 1))
X[2]  # is RV(Normal(0, 1))
```
but 
```
X = RV(PoissonProcessProbabilitySpace(1) * (Normal(0, 1) ** 2))
X[1]  # is RV(Normal(0, 1) ** 2)
```

**Comment by dlsun** [comment]
- How do we want Vector (or InfiniteVector) + ContinuousTimeFunction to behave (both for RV and result)? At first I thought this wouldn't make sense. But do we want (2, 3) + X(t) to return (2 + X(t), 3 + X(t))? Same for DiscreteTimeFunction.

I agree that that is one possible interpretation of (2, 3) + X(t), but I'm not sure it makes sense. What type of object would (2 + X(t), 3 + X(t)) be? It doesn't seem to behave like a random vector or a random process. For example, how would you plot it?

- What kind of Python object is a Symbulate result vector? Vector + [blank] works when Vector is a result vector, e.g. x + RV(Normal(0, 1)) returns RV-Vector for x = Poisson(2)**2.draw(). But how to replace x with constants, e.g. (2, 3) + RV(Normal(0, 1))? I tried numpy array but that's not it.

It's a `Vector` object. So you could do `Vector((2, 3)) + RV(Normal(0, 1))`.

I can actually make `(2, 3) + RV(Normal(0, 1))` work. But there's no way to make `(2, 3) + (0, 1)` work, so I'm not sure if enabling that notation would ultimately be more confusing. Let me know what you think.

- I'm assuming we only want to allow operations on Vectors with same length, so Vector + Infinite-Vector should not work, and it does not (i.e. no recycling).

Yes, that was the idea.

- Can you give me a few examples of DiscreteTimeFunction? I'm not sure how this is intended to work.

You specify the function X[n]. So `lambda n: n` at a sampling rate of `fs=2` would actually be the sampled version of the function `f(t) = 2t`.

- We now have ContinuousTimeFunction result. Are GaussianProcessResult and PoissonProcessResult special cases of CTF result? Will each special process have its own result type, or should there just be general CTF result?

Yes, they are both special cases (i.e., subclasses) of CTF. The reason for giving them their own class is that they store additional metadata. But they all share, for example, the same `.plot()` function. 

By the way, if `x` is a `GaussianProcessResult`, you can check that it is also a CTF using `isinstance(x, ContinuousTimeFunction)`.

- What are the intended "rules" for unpacking? Generally, X = RV(P * Q) gets unpacked like X[0] = RV(P), X[1] = RV(Q). But not if P and Q represent Scalar and Vector, in which case it gets unpacked like one big vector.

Right now, the rule is that scalars and vectors get concatenated into one big vector. Is that the behavior we want? Maybe we want `*` to return Tuples, but `**` to return Vectors? So `RV(Normal() * Normal() ** 2)` would return a tuple of two objects, the second of which is a vector of length 2? What do you think?

**Comment by kevindavisross** [comment]
- How do we want Vector (or InfiniteVector) + ContinuousTimeFunction to behave (both for RV and result)? At first I thought this wouldn't make sense. But do we want (2, 3) + X(t) to return (2 + X(t), 3 + X(t))? Same for DiscreteTimeFunction.

I agree that that is one possible interpretation of (2, 3) + X(t), but I'm not sure it makes sense. What type of object would (2 + X(t), 3 + X(t)) be? It doesn't seem to behave like a random vector or a random process. For example, how would you plot it?

  **Yes, it probably doesn't make sense.**

- What kind of Python object is a Symbulate result vector? Vector + [blank] works when Vector is a result vector, e.g. x + RV(Normal(0, 1)) returns RV-Vector for x = Poisson(2)**2.draw(). But how to replace x with constants, e.g. (2, 3) + RV(Normal(0, 1))? I tried numpy array but that's not it.

It's a `Vector` object. So you could do `Vector((2, 3)) + RV(Normal(0, 1))`.

I can actually make `(2, 3) + RV(Normal(0, 1))` work. But there's no way to make `(2, 3) + (0, 1)` work, so I'm not sure if enabling that notation would ultimately be more confusing. Let me know what you think.

  **Thanks.  No need to change notation; `Vector` is fine.**

- I'm assuming we only want to allow operations on Vectors with same length, so Vector + Infinite-Vector should not work, and it does not (i.e. no recycling).

Yes, that was the idea.

- Can you give me a few examples of DiscreteTimeFunction? I'm not sure how this is intended to work.

You specify the function X[n]. So `lambda n: n` at a sampling rate of `fs=2` would actually be the sampled version of the function `f(t) = 2t`.

  **I haven't tested this much out yet, but I will.**

- We now have ContinuousTimeFunction result. Are GaussianProcessResult and PoissonProcessResult special cases of CTF result? Will each special process have its own result type, or should there just be general CTF result?

Yes, they are both special cases (i.e., subclasses) of CTF. The reason for giving them their own class is that they store additional metadata. But they all share, for example, the same `.plot()` function. 

By the way, if `x` is a `GaussianProcessResult`, you can check that it is also a CTF using `isinstance(x, ContinuousTimeFunction)`.

  **I know you said implementing `ContinuousTimeFunction` was a pain, but I really like it.  Thanks for making it work!**

- What are the intended "rules" for unpacking? Generally, X = RV(P * Q) gets unpacked like X[0] = RV(P), X[1] = RV(Q). But not if P and Q represent Scalar and Vector, in which case it gets unpacked like one big vector.

Right now, the rule is that scalars and vectors get concatenated into one big vector. Is that the behavior we want? Maybe we want `*` to return Tuples, but `**` to return Vectors? So `RV(Normal() * Normal() ** 2)` would return a tuple of two objects, the second of which is a vector of length 2? What do you think?

  **Yes, I think that `*` should return Tuples.  I think that would enhance consistency with the other objects.**


A few more comments/issues; see the attached notebook for more details
[Random process overhaul - bugs.pdf](https://github.com/dlsun/symbulate/files/2358294/Random.process.overhaul.-.bugs.pdf)


- `BrownianMotion`: change to (drift=0, scale=1) (You already made the change for ProbSpace)
- For histograms, I'm getting " 'normed' kwarg is deprecated" warning, so it would be great if we could merge in Kien's changes which fixed this.
- There are some examples of vector-valued processes where unpacking and time-indexing can get confusing.  Say I want X to be a 2-d Brownian motion, and I want to generate 100 pairs at time 1.  But `X[1].sim(100)` generates 100 sample paths of the first coordinate
  - Is there a way to distinguish between time index and coordinate index?  Maybe not possible or desirable.  Is there a way to indicate all components of a vector, like `X[:]`, so `X[:][1.2]` returns vector at time 1.2? Or do we just need to unpack carefully?
- Should we allow transformations of processes with common functions using g(X) syntax?
- Negative indexing for vectors, e.g. `X[-2]`, - starting with the end.  Do we want to allow?
- Two examples giving errors that I can't figure out why

```
P = BrownianMotionProbabilitySpace(drift=2)
Q = BrownianMotionProbabilitySpace(drift=-2)
X = RV(P * Q)
S = RV(P * Q, sum)
(X & S).sim(10)
# "same prob space error"
```

```
P = Uniform(-pi, pi)
t = ContinuousTimeFunction()
Z = RV(P)
X = cos(2 * pi * t + Z)
X.sim(10).plot()
# TypeError: must be real number, not ContinuousTimeFunction
```

**Comment by kevindavisross** [comment]
- `X = RV((BrownianMotionProbabilitySpace(0, 1) ** 3) * (PoissonProcessProbabilitySpace(3) ** 3))` is also unpacking like a vector of length 6 instead of two tuples of length 3 each
- I think we would want to add a Vector to a vector-valued process.  But it's not working properly
```
B = RV(BrownianMotionProbabilitySpace() ** 3)
y = Vector((10, 100, 1000))
X = y + B
```
Note: I don't think vector-valued process functionality is essential to this version of Symbulate.  But so much does work already, that I'm trying to see how far we can push it.
- I haven't been able to figure out how to define a compound PoissonProcess, i.e. a PoissonProcess where the jump sizes are realizations of an InfiniteVector like`RV(Normal() ** inf)`.  Any ideas?
- I didn't mention previously, but you convinced me on 0-indexing for arrival and interarrival times for jump processes.

**Comment by kevindavisross** [comment]
Here's an example that involves several issues that I've mentioned above, like unpacking and 0-indexing.

I don't know how to define a compound Poisson process, so I tried to define a compound Poisson RV
```
P = (Normal(0, 1) ** inf) * Poisson(0.1)
X, N = RV(P)
Y = X.apply(cumsum)
Y[N].sim(1000)
```
This *almost* works.  The problem is that I want Y=0 when N=0, but here Y = X[0] if N=0 because of the 0-indexing.  I could solve the problem by appending 0 as the first entry of X.  I tried to do this with 
```
P = BoxModel([0], size=1) * (Normal(0, 1) ** inf)
X = RV(P)
N = RV(Poisson(0.1))
X, N = AssumeIndependent(X, N)
```
but `X` unpacks into two tuples --- like we've said we want it to do --- instead of a single vector (so I can't use `cumsum`).

So
- Is there a way to append vectors into a single vector?
- I think we should have a general protocol for unpacking, but should we allow this to be overridden?  Like with `vectorize` or `tupleize` functions?
- I have been trying to use `AssumeIndependent` as little as possible, instead trying to reflect the independence in the probability space.  I generally have been able to do this, though in some situations the `AssumeIndependent` syntax is easier.  But even if my BoxModel fix above worked, I wouldn't know how to do this example without `AssumeIndependent` or being able to override the unpacking (I would want BoxModel to go with Normal, but Poisson to be on its own).

**Comment by dlsun** [comment]
> Yes, I think that * should return Tuples. I think that would enhance consistency with the other objects.

Done. But just FYI, there are downsides to this approach. Now, `(Normal() ** 3).draw()` is a `Vector`, while `(Normal() * Normal() * Normal()).draw()` is a `Tuple`. This means that some operations, like `.sum()` will not be available for the latter. This is unavoidable because `*` is a binary operation. If we want both `Normal() * Normal()` and `Normal() * Normal() * Normal()` to return `Vector`s, then we'd have to allow multiple `Vector`s to collapse into one big `Vector`, as the code was before.

Let me know if you have any thoughts about which approach is better.

> BrownianMotion: change to (drift=0, scale=1) (You already made the change for ProbSpace)

Done.

> For histograms, I'm getting " 'normed' kwarg is deprecated" warning, so it would be great if we could merge in Kien's changes which fixed this.

I'll do this after merging this pull request.

> Is there a way to distinguish between time index and coordinate index? Maybe not possible or desirable. Is there a way to indicate all components of a vector, like X[:], so X[:][1.2] returns vector at time 1.2? Or do we just need to unpack carefully?

This is probably not worth doing until we implement vector-valued random processes.

> Should we allow transformations of processes with common functions using g(X) syntax?

This works already, except there was a bug, which I fixed. (See the discussion of the cosine example below.)

> Negative indexing for vectors, e.g. X[-2], - starting with the end. Do we want to allow?

This should work already. Are you saying we should disallow it?

> Two examples giving errors that I can't figure out why
> ```
> P = BrownianMotionProbabilitySpace(drift=2)
> Q = BrownianMotionProbabilitySpace(drift=-2)
> X = RV(P * Q)
> S = RV(P * Q, sum)
> (X & S).sim(10)
> # "same prob space error"
> ```

That's because you defined `P * Q` twice. That's two instances of the same probability space, not the same probability space. Just store `P * Q` in a variable, and make it common to both `X` and `S`.

> P = Uniform(-pi, pi)
> t = ContinuousTimeFunction()
> Z = RV(P)
> X = cos(2 * pi * t + Z)
> X.sim(10).plot()
> # TypeError: must be real number, not ContinuousTimeFunction

This was fixed by [this commit](https://github.com/dlsun/symbulate/pull/67/commits/024c3a8148bdd61ca8d8b98a2adf365108b2f9a6).

In case you're curious, the bug was this: Functions like `cos()` simply apply `math.cos()` to the `RV` or `TimeFunction`. The problem here was that `cos(2 * pi * t + Z)` is two-levels deep: it is an `RV` that returns a `TimeFunction`. We can't just apply `math.cos()` to the `RV` because you can't call `math.cos()` on a `TimeFunction`. I've fixed this problem by making `cos()` (and other functions) recursive. Now, it will keep applying `cos()` until it hits a scalar, at which point it calls `math.cos()`.

**Comment by kevindavisross** [comment]
I'm looking at the new unpacking now.  A few quick comments

- `isinstance(x, Tuple)` returns: 'Tuple' not defined, but `isinstance(x, tuple)` works.  What's the difference between `tuple` and `Tuple`?
- I see what you say about the downside to `*` unpacking as tuple, but the following still works
```
P = Poisson(1) * Poisson(2) * Poisson(3)
X = RV(P, sum)
```
and this also works
```
(Poisson(1) * Poisson(2) * Poisson(3)).sim(10).apply(sum)
```
Is that what you expected?  Seems great to me.
- In the compound Poisson example, I tried to append 0 with `0 & X`, but that doesn't work.  But maybe it could?  Joining two RV `X & Y` produces a tuple; maybe we could allow constants also?

**Comment by dlsun** [comment]
> isinstance(x, Tuple) returns: 'Tuple' not defined, but isinstance(x, tuple) works. What's the difference between tuple and Tuple?

`Tuple` is a subclass of `tuple` that is defined in Symbulate. The reason for having two classes is to distinguish between probability spaces that return a tuple and collections of outcomes. For example, if you define `P` to be the `DeckOfCards` probability space, then `P.draw()` returns a `tuple` outcome, like `(3, 'hearts')`. If you do `P ** 2`, you want the outcome to be like `Tuple([(3, 'hearts'), (2, 'diamonds')])`. If we didn't distinguish between `tuple` and `Tuple`, then the two tuples would collapse into a single tuple, i.e., `(3, 'hearts', 2, 'diamonds')`. It's probably too confusing to call one `tuple` and the other `Tuple`. If you have another idea for a name for a list of outcomes, let me know.

The reason `isinstance(x, Tuple)` doesn't work is because `Tuple` is not exported by the package. It's easy to export it, but does a user really have to define their own `Tuple`?

> I see what you say about the downside to * unpacking as tuple, but the following still works...

Yes, `sum` will still work, but many other functions will not. For example, compare the following:
```
P1 = Poisson(1) * Poisson(1) * Poisson(1)
X = RV(P1, cumsum)
X.draw()

P2 = Poisson(1) ** 3
Y = RV(P2, cumsum)
Y.draw()
```

> In the compound Poisson example, I tried to append 0 with 0 & X, but that doesn't work. But maybe it could? Joining two RV X & Y produces a tuple; maybe we could allow constants also?

I agree that we should support the notation `0 & X`. But that won't solve your problem where `X` returns an `InfiniteVector`, right? For that, I'm thinking about creating a `concat(...)` function that takes in any number of scalars and vectors (and possibly an `InfiniteVector` at the end) and concatenates them into a single `Vector` or `InfiniteVector`. What do you think of this interface?

**Comment by kevindavisross** [comment]
- I have done a fairly comprehensive test of the new unpacking protocol.  I think it works well; there is a clear, consistent logic to it.
- I see about `tuple` vs `Tuple`.  I don't know of a better name yet.  I don't think we have to export; I had just been wondering why I could call say `isinstance(x, InfiniteVector)` but not `isinstance(x, Tuple)`.
- Do we need to worry about differences between when something returns type `int` versus `numpy.int32`? Potential addition versioning issues?
- I like your `concat` idea.  
- I agree that vector-valued processes should be deferred, but I'm impressed but how much capability is already there.

**Comment by dlsun** [comment]
> I have done a fairly comprehensive test of the new unpacking protocol. I think it works well; there is a clear, consistent logic to it.

Great!

> I see about tuple vs Tuple. I don't know of a better name yet. I don't think we have to export; I had just been wondering why I could call say isinstance(x, InfiniteVector) but not isinstance(x, Tuple).

Okay. Let me know if you have a better name. I really want to distinguish it from `tuple`.

> Do we need to worry about differences between when something returns type int versus numpy.int32? Potential addition versioning issues?

Thanks for pointing this out. We do indeed need to worry about that. In [this commit](https://github.com/dlsun/symbulate/pull/67/commits/6ced524cbc043ebe1d48921adab0107f9abf1994), I have systematically replaced all references to `isinstance(x, int)` to `isinstance(x, numbers.Integral)`, which includes Numpy types. 

> I like your concat idea.

Done. See attached notebook. Let me know if you notice any bugs or have any suggestions.

[Concat and Joint Distributions.pdf](https://github.com/dlsun/symbulate/files/2363056/Concat.and.Joint.Distributions.pdf)


> Joining two RV X & Y produces a tuple; maybe we could allow constants also?

Also done. See the attached notebook.

**Comment by kevindavisross** [comment]
- I retested the binary operations after your recent changes, and added a few more tests.  Almost everything that should work does, but I still need to do more tests with DiscreteTimeFunction.
- The only exception: The following does NOT work because `B.draw()` returns `tuple` and `Y.draw()` returns `Vector`.  
```
Y, B = RV(Normal() ** 3 * BrownianMotionProbabilitySpace() ** 3)
X = Y + B
type(X.draw())
```
 But replace `** 3` with `** inf` in the above and it DOES work and returns `InfiniteVector`.  Should something like `BrownianMotionProbabilitySpace() ** 3` return `Vector` (of continuous time functions) rather than `tuple`?  That would be consistent with the general protocol that `**` returns Vector.  This might fall under "vector-valued processes should be deferred", but there does seem to be an inconsistency in the current version.
- To replace "Tuple", how about "ProductSpaceOutcome" or "ProductSpaceResult"?  (I realize `Normal() ** inf` is also a product space but returns Vector, so ProductSpace is not the greatest name.  But I'm having trouble thinking of something better.)
- I imagine it's not possible to apply `concat` in RV space, or you would have implemented it already.  But I think the compound Poisson example would be nicer as
```
P = Poisson(1) * (Normal() ** inf)
N, Z = RV(P)
X = concat(0, Z).apply(cumsum)
X[N].sim(1000).plot()
```
- This is getting into specific examples now, but another way around the above is if `cumsum` had an "initialize" option, like `y = x.cumsum(initialize=3)` would have `y[0]=3`, `y[1]=3+x[0]`, etc?  Then compound Poisson would be
```
P = Poisson(1) * (Normal() ** inf)
N, Z = RV(P)
X = Z.apply(cumsum(initialize=0))
X[N].sim(1000).plot()
```
- In general I think the consistency of the new unpacking protocol outweighs any convenience the old protocol might offer for specific examples.  The examples that I have thought of so far when I want to "override" the unpacking with `concat` all involve situations like the compound Poisson example where I want to basically supplant the 0-indexing and start with x[0]=0 
- I imagine there is a good reason, but why can't you pass a tuple into `concat`, like `concat((2, (2, 3), 3))` instead of `concat(2, (2, 3), 3)`?

**Comment by kevindavisross** [comment]
- I can't figure out how to define a process through time rescaling, like $X(t) = W(exp(t))$.  Any ideas?
- Would it be possible to add Multinomial distributions?  I might use in 305.
- Re: the int issue, is there a similar issue with float?
- I don't think this is necessary now, but just a thought: `**` takes priority in order of operations for unpacking, so `X = RV(BoxModel([0, 1, 2], size=2, replace=False) ** inf)` unpacks with `X[0]` a Vector of size 2.  But one might want to unpack it like `X, Y` where `X` is an InfiniteVector with the results of all the first draws.  Since we have `concat`, would it also make sense to have some kind of "transpose" or "reshape" functions?
- `(BivariateNormal() ** 3).draw()` returns `AttributeError: 'BivariateNormal' object has no attribute 'sim_fn'`  Same for `** inf`.  Seems like this should work like BoxModel example above.

**Comment by dlsun** [comment]
> Should something like BrownianMotionProbabilitySpace() ** 3 return Vector (of continuous time functions) rather than tuple? That would be consistent with the general protocol that ** returns Vector. This might fall under "vector-valued processes should be deferred", but there does seem to be an inconsistency in the current version.

Okay, I've made it so that `**` returns a `Vector`, always. This means that I have to allow `Vector` to store arbitrary objects (whereas I originally conceived of `Vector` as only storing numbers). But maybe this is for the better. You can now also do things like 
```
a = Vector([Vector([0, 1]), Vector([2, 3])])
a + a
```
Your Brownian motion example now works; I'm just worried that I might have broken something else in the meantime. Could you please check to make sure that this change doesn't break something else?

> To replace "Tuple", how about "ProductSpaceOutcome" or "ProductSpaceResult"? (I realize Normal() ** inf is also a product space but returns Vector, so ProductSpace is not the greatest name. But I'm having trouble thinking of something better.)

This name is on the right track, but a little too verbose for my tastes.

> I imagine it's not possible to apply concat in RV space, or you would have implemented it already. 

It actually shouldn't be too bad; I just didn't think of it as a use case. Let me think about the best way to implement this.

> This is getting into specific examples now, but another way around the above is if cumsum had an "initialize" option, like y = x.cumsum(initialize=3) would have y[0]=3, y[1]=3+x[0], etc? 

I'm not sure I like this. The usual behavior of cumsum is for it to start with the first element of the sequence being summed. What would the value of "initialize" be in this case?

> I imagine there is a good reason, but why can't you pass a tuple into concat, like concat((2, (2, 3), 3)) instead of concat(2, (2, 3), 3)?

Yes, I should fix this. I should also allow people to pass multiple arguments into `Vector`.

> I can't figure out how to define a process through time rescaling, like $X(t) = W(exp(t))$. Any ideas?

I can't think of any ways to do this right now either.

> Would it be possible to add Multinomial distributions? I might use in 305.

I think this is a good idea, but I don't have the bandwidth to do this. Do you think you can take this on? (It's straightforward, but requires some time.)

> Re: the int issue, is there a similar issue with float?

I tried to also fix all the float issues when I fixed the int issues. Let me know if you run into any problems.

> I don't think this is necessary now, but just a thought: ** takes priority in order of operations for unpacking, so X = RV(BoxModel([0, 1, 2], size=2, replace=False) ** inf) unpacks with X[0] a Vector of size 2. But one might want to unpack it like X, Y where X is an InfiniteVector with the results of all the first draws. Since we have concat, would it also make sense to have some kind of "transpose" or "reshape" functions?

I would prefer to defer this until later.

> (BivariateNormal() ** 3).draw() returns AttributeError: 'BivariateNormal' object has no attribute 'sim_fn' Same for ** inf. Seems like this should work like BoxModel example above.

Thanks for catching this. It is fixed now.

**Comment by kevindavisross** [comment]
> Your Brownian motion example now works; I'm just worried that I might have broken something else in the meantime. Could you please check to make sure that this change doesn't break something else?

I reran most of my recent notebooks.  There are some bugs.  Most notably, I'm getting many "This operation is only possible with results of consistent dimension" exceptions when trying to plot sample paths or take means.  A notebook with a few examples is attached.
[Random process bugs.pdf](https://github.com/dlsun/symbulate/files/2385397/Random.process.bugs.pdf)

Also, adding Vector to Vector-valued RV-CTF does not work properly (see example in attached), though this might fall under "wait till later"

> To replace "Tuple", how about "ProductSpaceOutcome" or "ProductSpaceResult"? (I realize Normal() ** inf is also a product space but returns Vector, so ProductSpace is not the greatest name. But I'm having trouble thinking of something better.)

> This name is on the right track, but a little too verbose for my tastes.

"ProductOutcome" any better?

> I imagine it's not possible to apply concat in RV space, or you would have implemented it already.

> It actually shouldn't be too bad; I just didn't think of it as a use case. Let me think about the best way to implement this.

`concat` for RV would be nice, but I don't think it's essential now.

> I'm not sure I like this. The usual behavior of cumsum is for it to start with the first element of the sequence being summed. What would the value of "initialize" be in this case?

I imagined usual cumsum would be `cumsum(initialize=None)`, but I didn't really like this idea either.  I would prefer the `concat` for RV method.

> Would it be possible to add Multinomial distributions? I might use in 305.

> I think this is a good idea, but I don't have the bandwidth to do this. Do you think you can take this on? (It's straightforward, but requires some time.)

Sure, I'll try to do this over the weekend.

**Comment by dlsun** [comment]
> I reran most of my recent notebooks. There are some bugs. Most notably, I'm getting many "This operation is only possible with results of consistent dimension" exceptions when trying to plot sample paths or take means. A notebook with a few examples is attached.
Random process bugs.pdf

Thanks for catching this big bug. It was caused by an older change; it had nothing to do with replacing tuples by Vectors. It should be fixed now.

> Also, adding Vector to Vector-valued RV-CTF does not work properly (see example in attached), though this might fall under "wait till later"

This example didn't work because the `*` operator returns a `Tuple`, not a `Vector`. The weird behavior is because addition of `Tuple`s is concatenation. I should change that behavior.

Working on some of the other issues now.

**Comment by kevindavisross** [comment]
I haven't run much yet, but `*` and `&` aren't working; problems with `join`?

image
[Tuple.pdf](https://github.com/dlsun/symbulate/files/2439435/Tuple.pdf)

**Comment by dlsun** [comment]
Thanks Kevin -- I think I just fixed that problem.

**Comment by kevindavisross** [comment]
I'm trying to remember where we left off.  Please correct me if I'm wrong, but I think we had decided that

- `*` unpacks as Tuple
- `**` unpacks as Vector
- `*` took priority in order of operations

This is what was happening before at least.  For example,

```
X = RV(Poisson(1) ** 2 * Normal() ** 2)
X[0] # Vector of length 2 ~ Poisson(1)**2
X[1] # Vector of length 2 ~ Normal()**2
X[0][0] # int ~ Poisson(1)
X[1][0] # float ~ Normal()
```
But now  `RV(Poisson(1) ** 2 * Normal() ** 2)` is behaving like one big vector of length 4.  Is this a change you intended to make?  If so, it will take me longer to check, because that's different than how I had been testing before.

**Pull request merged**
