### PR TITLE
Distr h liu

### PR DESCRIPTION
**Pull request by hliu26**

### CODE REVIEW

**Comment by kevindavisross** [comment]
I've tested the functionality and most everything seems to be working well; some examples are attached.  I'll let Dr. Sun review the actual code.

Some comments
- Add median, quantile in simulation space, e.g. `RV(Exponential(1)).sim(10000).median()`
- Add `.count(f)` to count based on critera determined by user defined function `f`; [we can already do this in simulation space](https://dlsun.github.io/symbulate/sim.html#count)
- See my previous email for more comments and more functions to add
[Statistics functions demo.pdf](https://github.com/dlsun/symbulate/files/1261144/Statistics.functions.demo.pdf)

**Comment by dlsun** [comment]
Hi Howard,

This looks great! I'm going to merge this PR, but could you start a new PR with some tests for these functions, in a file called math_test.py?

Thanks,
DS

**Comment by hliu26** [comment]
@dlsun I was wondering for the quantile function if the returned value should be within the tuple of numbers within the simulation? say (1, 2, 3, 4, 6, 7, 4, 7) and the 55th quantile comes out as something like 4.23 is that fine or should it be 4 (since 4.23 is not in the tuple)?

**Comment by dlsun** [comment]
I personally think it should be one of the numbers in the data set, but if that's what Numpy thinks it is, that's fine with me.

@kevindavisross What do you think?

**Comment by kevindavisross** [comment]
This issue concerns adding quantile in simulation space, right?  I agree that it should be an actual observed value.    But the discrepancy should only be an issue for small data sets.  If it's a pain to override numpy, I wouldn't worry about it.

**Pull request merged**
