### PR TITLE
Document inf prod, chi, t, f

### PR DESCRIPTION
**Pull request by JackConway1**
Added documentation on infinite products of probability spaces as well as chi-square, t, F distributions.

### CODE REVIEW

**Comment by dlsun** [comment]
I haven't reviewed this carefully, but one quick comment. Before you submit a Jupyter notebook, you should always "Restart and Run All" cells, starting from the top. That is, you should see the cells numbered in order, starting from [1], [2], [3], ....

Could you please go through your notebooks and "Restart and Run All"?

**Comment by kevindavisross** [comment]
Thanks, Jack.  Please revise based on the following.

- Jupyter notebook only displays the output of the last line (aside from plots).  So note that in your Chi-square example the mean and sd aren't displayed.
- To be consistent with the other distributions, define each distribution first by the density.  It is fine to only specify the functional form without the normalizing constants.  Like in the other examples, be sure to specify the parameters when you define e.g. "A (Student's) t distribution with m degrees of freedom" rather just "a t distribution".
- After the density definition show an example simulating directly from the distribution for different parameter values, like for Normal.
- Then you can say something like "A (Student's) t distribution is more conveniently defined via the following..." and give the alternate (usual) definition.
- Then you can do an example comparing simulating directly from the distribution versus the alternative definition, e.g.
(Z / (sqrt(Y / m))).sim(10000).plot(bins = 30)
RV(StudentT(df = m).sim(10000).plot(bins = 30)
- For Chi-square, before the density definition say "A Gamma distribution with shape parameter m/2 and rate parameter 1/2 is also known as a chi-square distribution with m degrees of freedom."
- You can remove the chi-square is additive example (it would be better in the Gamma section anyway).
- Note for the textbook: We will add the means and variances for all the distributions.  T and F are first examples for which it is possible that mean or variance is not defined, so we will need to add notes about that. 
- This section is getting long, so please add "Back to contents" cells after each distribution (including the ones that were already  there.)
- Always use capital letters for RV and small letter for simulated values, T vs t.  
- Put commands for plots on separate lines
- You don't have to save the results and then plot, you can do X.sim(10000).plot()
- Revise for grammar.  Read out loud and make sure it reads smoothly (e.g. be sure to include articles a, the, etc).

**Comment by kevindavisross** [comment]
I need to think of a better example for infinite product spaces.  But please go ahead and make the changes in my other comment.

**Comment by JackConway1** [comment]
I updated common.ipynb for Chi-square, t, and f to address the changes above. This included adding densities, as well as changed the cells from saving the values to directly plotting them. I added the "back to contents tab" at the end of each distribution and used the restart and run all command on both of the notebooks (probspace and common).

**Comment by kevindavisross** [comment]
- Move Beta section until after F, so that Chi-square comes right after Gamma.
- Use \left( and \right) instead of ( and ), e.g. when \frac is inside (); the height of the parentheses will adjust to fit whatever is inside.
- Plots: use bins = 30 to get smoother shapes.
- Chi-square: Try m=2 instead of m=1 since m=1 throws off the scale.
- t density: you don't need the \cdot after the constant (also in F).  Change t to x.  Use a negative exponent instead of 1/.
- t plot: use more bins.  m = 3 is throwing off scale.  Try different values to get a nice looking plot.
- I don't think we have used the shorthand Z ~ N(0,1) anywhere on the page (and maybe not in the whole doc).  So write out in words: "If Z has a Normal(0,1) distribution"  
- t and F: change "said to have" to "has"
- Use spaces after commas, in Normal part of t example and in general
- Use smaller df for the second t example
- F: "degrees of freedom in the numerator" instead of "numerator degrees of freedom"
- F examples: change bins and experiment with different parameter values to get nicer looking plots
- remove "denoted F_{m,n}".
- Put \quad between densities and x>0 to create some space.

**Comment by JackConway1** [comment]
Made the changes listed above. Currently adding .cdf() and .pdf*() to common.ipynb.

**Comment by kevindavisross** [comment]
- Please double check that you have made all the changes above.  I caught a few that had not been made.
- In probspace, delete your example for infinite product space and replace with the following.  _Example._ Infinitely many independent Normal(0, 1) values.
P = Normal(mean = 0, var =1) ** inf
P.draw()
- Chi-square density: exponent on x is (m/2 - 1)
- Denominator of constant in t dist: use \, after \sqrt{} to create a little space before \Gamma.
- t plot still not great: use m = [3, 20] so they don't overlap so much.
- Remove the \chi^2 notation and replace with words from the second t definition
- F: "degrees of freedom in the numerator" instead of "numerator degrees of freedom"
- F second def, replace \chi^2 notation with words
- Put the anchors and Back to contents links in the same cell e.g.
<a id='process'></a>
[Back to contents](#contents)

**Comment by kevindavisross** [comment]
I haven't review yet, but there were a few more changes I meant to add to intro.ipynb.
- Change "Formatting..." to "Displaying output"
- Follow the first sentence ("Jupyter notebooks only..." with a cell like
1 + 2
2 / 3
"To display the output of multiple commands, place the commands in separate cells.  (Cells can be added using the + button on the toolbar.)"

"Output can be formatted and displayed using print statements (add a link to a site like [this one](https://docs.python.org/3/tutorial/inputoutput.html).")
print('{:.3f}'.format(4/6))

**Comment by kevindavisross** [comment]
Common.ipynb
- Remove the parentheses from exponent of x in chisquare (this was my mistake)
- The anchor to Joint distributions is with Beta; move it back to right before Joint distributions.

Probspace
- Replace text before inf prob example with: Infinite independent copies of a probability space can be created using `** inf`.
- Add a space before and after ** in the code

Intro
- Add back the line "Jupyter notebooks only display the output of the last line of code in a cell (aside from code which produces a plot)."
- Separate is with an a in the middle, not e.
- Remove the prob anchor before Displaying output

Make those changes, change any .ipynb links to .html, then download and in Jupyter save each file as .html.  Check that all the links work in the .html files, especially ones you added or changed.  After you are satisfied that everything works, upload everything to Github, then I will merge.

**Pull request merged**
