### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by dlsun**

### CODE REVIEW

**Comment by dlsun** [comment]
@kevindavisross Most of these changes should be no-ops from the user's perspective. However, some variable names have changed:

- Every instance of a function is now called `func`. (Before, it would sometimes be called `fun` and other times be called `fn`.
- The argument `probSpace` has been changed to `prob_space` everywhere. (This is a requirement of the Python style guide. Let me know if you'd prefer an alternative name.)

**Comment by dlsun** [comment]
@kevindavisross 

With this code refactor, all of the methods that work on `Results` (e.g., `abs`, `mean`, `var`, `skew`, `count_eq`, `count_lt`) should all work on `Tuple` as well. One exception is `standardize`, which is only implemented for `Results`, not for `Tuple`.

I also added a few more functions: `round`, `math.floor`, `math.ceil`. These should all work when you call them on an `RV`, `Results`, or `Tuple` object.

**Comment by kevindavisross** [comment]
Sorry, didn't mean to close.

**Comment by dlsun** [comment]
Thanks for catching that bug with GaussianProcess. It was indeed due to a leftover `fn` that was not changed to `func`. That's now been fixed.

`count_lt` and `filter_lt` are a mess right now when each result is a `Tuple` (or a `Vector`). That's because the  `<` operator is actually used to sort `Tuple`s, which we need to get `.tabulate()` to come out in the right order. So right now it does some kind of dictionary sorting. You'll notice that `count_gt` and `filter_gt` (and the other comparison operators) don't work at all. I don't have a good solution for this yet, but I'm thinking about it.

`.mean()` and other statistical operations currently only work for scalar, tuple/vector, or function-valued outputs. It would be quite some work to get it to work for other output types (in your example, you have a tuple of a vector and a scalar).

I exported `ceil` and `floor` so that they are now available without calling `math.ceil` and `math.floor`.

Please let me know if you spot anything else!

**Comment by kevindavisross** [comment]
I've done a pretty thorough check.   Most everything looks really good, but I did notice a few issues.
[Refactor_bugs3.pdf](https://github.com/dlsun/symbulate/files/2771898/Refactor_bugs3.pdf)


- Bug in simulating from `Pareto`.  The `self.draw=draw` line should be removed?
- Bugs with `concat`.  Your [examples here](https://github.com/dlsun/symbulate/pull/67#issuecomment-419616368) don't work now.
- Issue with calling X(omega) like a function where X is arrival_times of a stochastic process; see attached

A few questions:

- Should the list of statistical functions available be the same for RV space and for simulation space?  A few - `trimmed_mean`, `orderstatistics`, `moment` - are available in RV space but not sim space.  I'm fine if we remove them from RV space.
- For a stochastic process like `X = RV(PoissonProcessProbabilitySpace(1) ** 2)`, `X[0]` returns the first component for all times.  Should it be possible to return all components for a single time?  Something like `X[:][2.3]`.
- In GaussianProcessProbSpace should `mean_fn` be `mean_func`?  Same for `cov_fn`.

Just checking that the following are not included.  I don't think any of the following functionality is necessary now.  Just want to confirm it's intentional and not bugs.

- Unpacking results objects
- Time indexing in simulation space (example attached)
- .get() with multiple values, e.g. `x.get(list(range(10)))`

**Comment by dlsun** [comment]
Thanks for pointing out the bugs with Pareto and `concat`. Both are now fixed.

The `Y(omega)` wasn't actually a bug. You had `omega = P.sim(1)`, which returns a `Results` object of length 1; if you instead replace this by `omega = P.draw()`, your example works.

> Should the list of statistical functions available be the same for RV space and for simulation space? A few - trimmed_mean, orderstatistics, moment - are available in RV space but not sim space. I'm fine if we remove them from RV space.

Sorry, these don't seem to be available in `RV` space either? They are functions in `math.py`, which needs to be cleaned up, but I'll do that after this release (it's not a priority).

> For a stochastic process like X = RV(PoissonProcessProbabilitySpace(1) ** 2), X[0] returns the first component for all times. Should it be possible to return all components for a single time? Something like X[:][2.3].

Perhaps, but not for this release.

> In GaussianProcessProbSpace should mean_fn be mean_func? Same for cov_fn.

Yes, thanks for reminding me about this. This was on my to-do list. It's now done.

> Just checking that the following are not included. I don't think any of the following functionality is necessary now. Just want to confirm it's intentional and not bugs.

> - Unpacking results objects

Yes, this is not hard, but I prefer to defer it until later.

> - Time indexing in simulation space (example attached)

Also not hard, but I prefer to defer it until later.

> - .get() with multiple values, e.g. x.get(list(range(10)))

I made this work -- and much more. In fact, I now consistently allow subsetting by a list of values. For example, the following code didn't work previously, but now it does:

```
X = RV(Normal() ** 5)
X[[2, 3, 4]].draw(), X.draw()[[2, 3, 4]]
```

**Pull request merged**
