### PR TITLE
changed n= 0 in binomial

### PR DESCRIPTION
**Pull request by hliu26**

### CODE REVIEW

**Comment by dlsun** [comment]
Tests?

**Comment by hliu26** [comment]
@dlsun I'm not sure what you mean by tests. Unittests or the Notebook tests?

I thought it was agreed to allow n = 0 because it works but scipy just prints an error message

**Comment by dlsun** [comment]
Please send me notebook tests verifying that the change works. In general, we should not approve any changes if there aren't accompanying tests proving that the code works as intended. Even though your change is minor and looks correct to me, I could be missing something. The only way to know for sure is to test it out.

**Comment by hliu26** [comment]
Oh okay. Here’s the notebook below for testing Binomial.

**Comment by dlsun** [comment]
File didn't attach.

**Comment by hliu26** [comment]
Let me know if this one attached, it showed up for me in the previous email.

**Comment by dlsun** [comment]
Nope. Try attaching it on Github rather than replying directly to the email.

**Comment by hliu26** [comment]
[Dist_Binomial_Checking.ipynb.zip](https://github.com/dlsun/symbulate/files/1160458/Dist_Binomial_Checking.ipynb.zip)

**Comment by dlsun** [comment]
Howard, please attach a notebook containing your tests for just this one change. I don't need to see all of your Binomial tests.

Also, whenever you attach a file, Github gives you a URL. Please copy and paste that URL here: http://nbviewer.jupyter.org/, press Go, and copy the URL of the resulting page. Replace the Github URL with this new URL. This will allow everyone to view the notebook in a browser without having to download it.

**Comment by hliu26** [comment]
When I try to drag just the .ipynb file, github doesn't support that file. So I compress it into a zip to get the url, but then I get an error for trying to use that url in nbviewer. I also tried obtaining a shareable link of just the .ipynb file but it says the page does not exist. Should I just reupload the test file onto here again despite needing to download it?

**Comment by dlsun** [comment]
Yeah, if it won't let you upload .ipynb files, then you'll just have to upload the .zip file. I'll think of a better solution, but in the meantime, please just upload the .zip file.

**Comment by hliu26** [comment]
[Binomial_n_0.ipynb.zip](https://github.com/dlsun/symbulate/files/1160588/Binomial_n_0.ipynb.zip)

**Comment by hliu26** [comment]
For future uses would converting it to pdf be any better?

**Comment by dlsun** [comment]
Yeah, converting to PDF would be great.

**Comment by hliu26** [comment]
Okay, I'll do that next time.

**Comment by dlsun** [comment]
Okay, this PR looks good to me. Merging.

**Pull request merged**
