### PR TITLE
implemented MakeIndependent

### PR DESCRIPTION
**Pull request by dlsun**
Notebook demonstrating new functionality: [MakeIndependent.pdf](https://github.com/dlsun/symbulate/files/1217257/MakeIndependent.pdf)

### CODE REVIEW

**Comment by kevindavisross** [comment]
Looks awesome!  I've tried a bunch of things; some of my examples are attached.  Most things seem to be working fine; I only encountered one issue (see below).  There were some examples I couldn't immediately figure out how to do (e.g. define a compound Poisson process), but I don't think it had anything to do with MakeIndependent not working properly.  Most of the examples involved RandomProcesses, which might change anyway if we change from process to probability space (e.g. RandomProcess(PoissonProcess(1)) vs PoissonProcess(1)).

Issue:
- If MakeIndependent is applied to two PoissonProcesses, then .ArrivalTimes() doesn't work.  See the attached for more details.

A few comments
- The first example in the attachment is related to thinning a Poisson process.  @cenonn  and @hliu26  do you think you can make it work?  I think it just involves writing the proper function.
- I'm not sure how I feel about the wording "MakeIndependent".  Is "AssumeIndependent" any better?  Something else?
- @dlsun  You mentioned earlier you might be able to have just `MakeIndependent(X, Y)` rather than `X, Y = MakeIndependent(X, Y)`.  Was the first syntax not possible?
- If you define X, Y, Z and call MakeIndependent(X, Y) followed by MakeIndependent(X, Z) then X and Y are no longer defined on the same probability space, because the second call redefines X and Z to be on the same space.  I'm sure this was intended and I think it is exactly how it should be.  But it might be a common mistake, so our warnings and FAQ should reflect it.  (Problem is solved with MakeIndependent(X, Y, Z).)
- Will we eventually implement product `*` syntax for independent random processes?  `M, N = PoissonProcess(1) * PoissonProcess(2)`.  Maybe if/after we make the switch mentioned above?  (We might need to rethink the way we do random processes in general.)
- MakeIndependent only works for RVs, not probability spaces. Which is probably the way it should be.

[MakeIndependent comments.pdf](https://github.com/dlsun/symbulate/files/1218639/MakeIndependent.comments.pdf)

**Comment by dlsun** [comment]
Thanks Kevin. One quick point: the reason .ArrivalTimes() doesn't work anymore is because Symbulate has no way of knowing that the sum of two Poisson Processes is again a Poisson process. So if we wanted to implement that functionality, we'd have to manually program that in (i.e., "for the __add__ method of a Poisson Process, if the other object is a PoissonProcess, the result is another Poisson Process").

**Comment by cenonn** [comment]
I tried a couple things with random variables and it seemed to work as expected. I do agree with Dr. Ross that 'AssumeIndependent' would be better wording. 

I don't have any experience with random processes. Would you happen to know of a good place to start learning about them?

**Comment by kevindavisross** [comment]
@cenonn : You have access to my PL site for Stat 405 in spring which has all my handouts and materials.  I'm biased, but I think that's a good place to start for random processes.

I can check more on the random process side, but you and @hliu26 should check RV stuff.  The example in my earlier attachment I asked you to look at doesn't require any knowledge of random processes.

**Comment by dlsun** [comment]
I renamed the function to AssumeIndependent. I also added a check that all of the RVs and RandomProcesses are currently defined on different probability spaces. (The behavior can be weird if two RVs are currently defined on the same probability space.) Please take a look.

[AssumeIndependent.pdf](https://github.com/dlsun/symbulate/files/1224152/AssumeIndependent.pdf)

**Comment by dlsun** [comment]
Thanks Kevin, I added an error message if the user passes in something other than an RV or a RandomProcess. I verified that everything still works. Now merging.

**Pull request merged**
